// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bznmrdzhsmuraqywfdpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6bm1yZHpoc211cmFxeXdmZHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDc3NzksImV4cCI6MjA2MDYyMzc3OX0.lXh1RLEndQKahWcsTmdr2lBOvFyfQPGzMOVuEEwgkOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);